export const GET_ROUTES = "GET_ROUTES";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_FAILURE = "GET_ROUTES_FAILURE";

export const GET_BAR_GAME = "GET_BAR_GAME";
export const GET_BAR_GAME_SUCCESS = "GET_BAR_GAME_SUCCESS";
export const GET_BAR_GAME_FAILURE = "GET_BAR_GAME_FAILURE";

export const GET_ROUTE_DETAIL = "GET_ROUTE_DETAIL";
export const GET_ROUTE_DETAIL_SUCCESS = "GET_ROUTE_DETAIL_SUCCESS";
export const GET_ROUTE_DETAIL_FAILURE = "GET_ROUTE_DETAIL_FAILURE";

export const GET_FINAL_DETAIL = "GET_FINAL";
export const GET_FINAL_DETAIL_SUCCESS = "GET_FINAL_DATA_SUCCESS";
export const GET_FINAL_DETAIL_FAILURE = "GET_FINAL_DATA_FAILURE";

export const GET_TEAM_DETAIL = "GET_TEAM_DETAIL";
export const GET_TEAM_DETAIL_SUCCESS = "GET_TEAM_DETAIL_SUCCESS";
export const GET_TEAM_DETAIL_FAILURE = "GET_TEAM_DETAIL_FAILURE";

export const GET_USERNAMES = "GET_USERNAMES";
export const GET_USERNAMES_SUCCESS = "GET_USERNAMES_SUCCESS";
export const GET_USERNAMES_FAILURE = "GET_USERNAMES_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_SUCCESS = "RESEND_EMAIL_SUCCESS";
export const RESEND_EMAIL_FAILURE = "RESEND_EMAIL_FAILURE";

export const VERIFY_TOKEN = "VERIFY_TOKEN";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";

export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN";

export const USER_DATA = "USER_DATA";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";