export const GET_ROUTES = "GET_ROUTES";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_FAILURE = "GET_ROUTES_FAILURE";

export const GET_BAR_GAME = "GET_BAR_GAME";
export const GET_BAR_GAME_SUCCESS = "GET_BAR_GAME_SUCCESS";
export const GET_BAR_GAME_FAILURE = "GET_BAR_GAME_FAILURE";
export const SAVE_ANSWER = "SAVE_ANSWER";
export const SAVE_ANSWER_SUCCESS = "SAVE_ANSWER_SUCCESS";
export const RESET_GAME = "RESET_GAME";

export const GET_ROUTE_DETAIL = "GET_ROUTE_DETAIL";
export const GET_ROUTE_DETAIL_SUCCESS = "GET_ROUTE_DETAIL_SUCCESS";
export const GET_ROUTE_DETAIL_FAILURE = "GET_ROUTE_DETAIL_FAILURE";

export const GET_FINAL_DETAIL = "GET_FINAL";
export const GET_FINAL_DETAIL_SUCCESS = "GET_FINAL_DATA_SUCCESS";
export const GET_FINAL_DETAIL_FAILURE = "GET_FINAL_DATA_FAILURE";

export const RESET_TEAM_STATE = "RESET_TEAM_STATE";
export const GET_TEAM_DETAIL = "GET_TEAM_DETAIL";
export const GET_TEAM_DETAIL_SUCCESS = "GET_TEAM_DETAIL_SUCCESS";
export const GET_TEAM_DETAIL_FAILURE = "GET_TEAM_DETAIL_FAILURE";
export const FIND_TEAM = "FIND_TEAM";
export const FIND_TEAM_SUCCESS = "FIND_TEAM_SUCCESS";
export const FIND_TEAM_FAILURE = "FIND_TEAM_FAILURE";


export const SAVE_TEAM_DATA = "SAVE_TEAM";
export const SAVE_TEAM_DATA_SUCCESS = "SAVE_TEAM_SUCCESS";
export const SAVE_TEAM_DATA_FAILURE = "SAVE_TEAM_FAILURE";
export const ADD_MEMBER = "ADD_MEMBER";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "ADD_MEMBER_FAILURE";

export const RESET_TOAST = "REMOVE_TOASTS";
export const SHOW_TOAST = "SHOW_TOAST";

export const GET_USERNAMES = "GET_USERNAMES";
export const GET_USERNAMES_SUCCESS = "GET_USERNAMES_SUCCESS";
export const GET_USERNAMES_FAILURE = "GET_USERNAMES_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_SUCCESS = "RESEND_EMAIL_SUCCESS";
export const RESEND_EMAIL_FAILURE = "RESEND_EMAIL_FAILURE";

export const VERIFY_TOKEN = "VERIFY_TOKEN";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";

export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN";

export const USER_DATA = "USER_DATA";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_USER_DATA_SUCCESS = "SAVE_USER_DATA_SUCCESS";
export const SAVE_USER_DATA_FAILURE = "SAVE_USER_DATA_FAILURE";

export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILURE = "REMOVE_USER_FAILURE";

export const REMOVE_TEAM = "REMOVE_TEAM";
export const REMOVE_TEAM_SUCCESS = "REMOVE_TEAM_SUCCESS";
export const REMOVE_TEAM_FAILURE = "REMOVE_TEAM_FAILURE";

export const GET_TAPA_DETAIL = "GET_TAPA_DETAIL";
export const GET_TAPA_DETAIL_SUCCESS = "GET_TAPA_DETAIL_SUCCESS";
export const GET_TAPA_DETAIL_FAILURE = "GET_TAPA_DETAIL_FAILURE";
export const UPDATE_TAPA = "UPDATE_TAPA";